### PR TITLE
Fix rmd preview chunk colouring

### LINKED ISSUE #866: Rmd preview fails if chunk-background setting is empty
With the setting `"r.rmarkdown.chunkBackgroundColor": ""`, the Rmd live preview fails in dark mode.

This can be solved by adding `const regOut = chunkCol.match(colReg) || [];` in [rmarkdown/preview.ts](https://github.com/ManuelHentschel/vscode-R/blob/b47e93b751896b743e269fd9a95189ae74af9f5e/src/rmarkdown/preview.ts#L89-L92), but then the code blocks are rendered with a white background and somewhat difficult to read.

### PR DESCRIPTION
**Pull request by ElianHugh**
# What problem did you solve?

Resolves #866. If a chunk background colour is not defined, fall back to a vscode theme colour

## How can I check this pull request?

``````
```
A non-code chunk
```

```{r}
1:100
```
``````

### CODE REVIEW

File: src/rmarkdown/preview.ts [hunk 1]
```diff
@@ -86,10 +86,16 @@ class RMarkdownPreview extends vscode.Disposable {
...
-        const outCol = `rgba(${regOut[0] ?? 100}, ${regOut[1] ?? 100}, ${regOut[2] ?? 100}, ${Number(regOut[3]) + 0.05 ?? .5})`;
+        let chunkCol = String(config().get('rmarkdown.chunkBackgroundColor'));
+        let outCol: string;
+        if (chunkCol) {
+            const colReg = /[0-9.]+/g;
+            const regOut = chunkCol.match(colReg);
+            outCol = `rgba(${regOut[0] ?? 100}, ${regOut[1] ?? 100}, ${regOut[2] ?? 100}, ${Number(regOut[3]) + 0.05 ?? .5})`;
+        } else {
+            chunkCol = 'var(--vscode-selection-background)';
+            outCol = 'var(--vscode-selection-background)';
```
Comment (renkun-ken) [inline src/rmarkdown/preview.ts:97]: Should we make the chunk and output appear slightly different?

image

image

**Comment by renkun-ken** [comment]
Looks like we should use something like `rgba(128, 128, 128, 0.1)` and `rgba(128, 128, 128, 0.05)` to get a more consistent coloring under different themes.

File: src/rmarkdown/preview.ts [hunk 2]
```diff
@@ -86,10 +86,16 @@ class RMarkdownPreview extends vscode.Disposable {
         this.htmlLightContent = $.html();
 
         // make the output chunks a little lighter to stand out
-        const chunkCol = String(config().get('rmarkdown.chunkBackgroundColor'));
-        const colReg = /[0-9.]+/g;
-        const regOut = chunkCol.match(colReg);
-        const outCol = `rgba(${regOut[0] ?? 100}, ${regOut[1] ?? 100}, ${regOut[2] ?? 100}, ${Number(regOut[3]) + 0.05 ?? .5})`;
```
Comment (renkun-ken) [inline src/rmarkdown/preview.ts:92]: I suspect that the alpha channel should be something like `${Number(regOut[3]) - 0.05 ?? .05}` to make the output more like the background. In light themes, the default rendering looks like the code chunk is more highlighted than the output from the background.

File: src/rmarkdown/preview.ts (hunk 1 above)
Comment (renkun-ken) [reply src/rmarkdown/preview.ts:97]: Looks like we should use something like `rgba(128, 128, 128, 0.1)` and `rgba(128, 128, 128, 0.05)` to get a more consistent coloring under different themes.

**Review by renkun-ken — APPROVED** [review]
LGTM
